name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  subscriptionId: 68a33762-d609-4c0d-8155-85dc7542da37

jobs:
  armDeployStaging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    env:
      resource_group_name: rg-stg-githubactions
      location: Central India
    environment:
      name: staging

    steps:
      - uses: actions/checkout@v3

      - name: Azure/Login
        uses: Azure/login@v1
        with:
          creds: ${{  secrets.AZURE_CREDENTIALS}}

      - name: Deploy Resource Group ${{ env.resource_group_name }} 
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.subscriptionId}}
          region: "${{ env.location }}"
          template: ./arm-templates/resourcegroup.json
          parameters: 
            resourceGroupName=${{ env.resource_group_name }}
          deploymentName: ${{ env.resource_group_name }}

      - name: Deploy Storage Account 
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ env.subscriptionId}}
          template: ./arm-templates/storageaccount.json
          parameters: 
            sku=Standard_LRS
            storageAccountName=globostg0022
            location=${{ env.location}}
          deploymentMode: incremental

      - name: Deploy Virtual Machine 
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ env.subscriptionId}}
          template: ./arm-templates/virtualmachine.json
          parameters: 
            adminPassword=${{ secrets.UBUNTU_ADMIN_PASSWORD}}
          deploymentMode: incremental

  armDeployProduction:
      name: Deploy to Production
      runs-on: ubuntu-latest
      env:
        resource_group_name: rg-prod-githubactions
        location: East India
      environment:
        name: production
      
      needs: armDeployStaging

      steps:
        - uses: actions/checkout@v3

        - name: Azure/Login
          uses: Azure/login@v1
          with:
            creds: ${{  secrets.AZURE_CREDENTIALS}}

        - name: Deploy Resource Group ${{ env.resource_group_name  }} 
          uses: Azure/arm-deploy@v1
          with:
            scope: subscription
            subscriptionId: ${{ env.subscriptionId}}
            region: "${{ env.location }}"
            template: ./arm-templates/resourcegroup.json
            parameters: 
              resourceGroupName=${{ env.resource_group_name }}
            deploymentName: ${{ env.resource_group_name }}

        - name: Deploy Storage Account 
          uses: Azure/arm-deploy@v1
          id: storageAccountDeploy
          with:
            scope: resourcegroup
            resourceGroupName: ${{ env.resource_group_name }}
            subscriptionId: ${{ env.subscriptionId}}
            template: ./arm-templates/storageaccount.json
            parameters: 
              sku=Standard_LRS
              storageAccountName=globostg0033
              location=${{ env.location}}
            deploymentMode: incremental

        - name: Deploy Virtual Machine 
          uses: Azure/arm-deploy@v1
          with:
            scope: resourcegroup
            resourceGroupName: ${{ env.resource_group_name }}
            subscriptionId: ${{ env.subscriptionId}}
            template: ./arm-templates/virtualmachine.json
            parameters: 
              adminPassword=${{ secrets.UBUNTU_ADMIN_PASSWORD}}
            deploymentMode: incremental


      
            

